apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache
  namespace: stardew-vision
spec:
  storageClassName: gp3-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
